name: ci
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or ref to run against (defaults to current branch)'
        required: false
        default: ''

  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    uses: jamesandrewmyers/aws-devops/.github/workflows/python-lambda-ci.yml@v1.0.0
    with:
      app-dir: '.'
      req-file: 'requirements.txt'
      python-version: '3.11'
      run-tests: false
